In [58]:
# Neste modulo de classificação vou fazer uma abordagem diferente devido na ultima atividade ter me perdido e passado horas e horas para fazer a atividade devido a um erro de arrendodamento e logaritimo em dados com uma 'calda'. Pretendo dar uma revisada no modulo de regressão linear posteriormente.
# Dei uma olhada nas atividades e vou dar uma olhada nas video aulas enquanto faço as anotações.

# Neste modulo sera abordado um modelo de predição de saida de clientes de uma empresa de telefonia.
# Neste caso sera uma classificação binaria, onde a previsão é se o cliente vai cancelar ou não. sendo 1 certeza de cancelar.

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

df = pd.read_csv(data)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [60]:
# Padronizando as informações das colunas e nomes em colunas.
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [61]:
df.dtypes
# observamos que possui uma coluna 'totalcharges' que possui numeros mas está caracterizada como string.

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [62]:
# Transformando com pandas os valores em numeros e qualquer erro que houver ignorar se não for numerico.
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')

# Como possui clientes que entraram nesse mes ainda, não possui valores lançados em 'totalcharges' por isso simplificaremos esse valor para 0
df.totalcharges = df.totalcharges.fillna(0)

In [63]:
# Transformando sim em 1 e não em 0. Para podermos usar no target do nosso modelo.
df.churn = (df.churn == 'Yes').astype(int)

In [64]:
from sklearn.model_selection import train_test_split
# Montando o campo de treino, validação e teste do modelo.

df_full_train,df_test = train_test_split(df, test_size=0.2, random_state=1)
len(df_full_train), len(df_test)

(5634, 1409)

In [65]:
df_train,df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val) , len(df_test)

(4225, 1409, 1409)

In [66]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [67]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [68]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [69]:
df_full_train = df_full_train.reset_index(drop=True)

In [70]:
df_full_train.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

churn
0    5174
1    1869
Name: count, dtype: int64

churn
0    4113
1    1521
Name: count, dtype: int64